// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwVPuAXzDUZEZynCpIRK7EoaEgFYe7bM',
    appId: '1:389387411447:web:2139673049e944c00f98f2',
    messagingSenderId: '389387411447',
    projectId: 'self-driving-intrusions',
    authDomain: 'self-driving-intrusions.firebaseapp.com',
    storageBucket: 'self-driving-intrusions.appspot.com',
    measurementId: 'G-EV2DY7F5H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2hq91sWvZHZCMLAUaKIPB_D8lcI1ixgc',
    appId: '1:389387411447:android:2ff2517683f9792a0f98f2',
    messagingSenderId: '389387411447',
    projectId: 'self-driving-intrusions',
    storageBucket: 'self-driving-intrusions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZWNr_vWTKzU92Iyl0O70FYX5vae9rLk',
    appId: '1:389387411447:ios:016589743ef14f3d0f98f2',
    messagingSenderId: '389387411447',
    projectId: 'self-driving-intrusions',
    storageBucket: 'self-driving-intrusions.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZWNr_vWTKzU92Iyl0O70FYX5vae9rLk',
    appId: '1:389387411447:ios:016589743ef14f3d0f98f2',
    messagingSenderId: '389387411447',
    projectId: 'self-driving-intrusions',
    storageBucket: 'self-driving-intrusions.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgwVPuAXzDUZEZynCpIRK7EoaEgFYe7bM',
    appId: '1:389387411447:web:f53a53cb08ae02d70f98f2',
    messagingSenderId: '389387411447',
    projectId: 'self-driving-intrusions',
    authDomain: 'self-driving-intrusions.firebaseapp.com',
    storageBucket: 'self-driving-intrusions.appspot.com',
    measurementId: 'G-FVNBFGYVZC',
  );
}
